# Generated by Django 3.2.6 on 2021-10-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dTruelt_phone_number',
            new_name='default_phone_number',
        ),
    ]
