# Generated by Django 3.2.6 on 2021-09-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='Order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='Product',
            new_name='product',
        ),
    ]
